kind: Deployment
apiVersion: apps/v1
metadata:
  name: food-delivery-backend-deployment
  namespace: food-delivery
  labels:
    app: food-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-backend
  template:
    metadata:
      labels:
        app: food-backend
    spec:
      containers:
        - name: food-delivery-backend
          image: hyysuresh/food-delivery-backend:20
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: backend-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"