kind: Deployment
apiVersion: apps/v1
metadata:
  name: food-delivery-admin-deployment
  namespace: food-delivery
  labels:
    app: food-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-admin
  template:
    metadata:
      labels:
        app: food-admin
    spec:
      containers:
        - name: food-delivery-admin
          image: hyysuresh/food-delivery-admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
