apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaatnikafood-tls
  namespace: food-delivery
spec:
  dnsNames:
    - jaatnikafood.food
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  secretName: jaatnikafood-tls
  usages:
    - digital signature
    - key encipherment 